monitor.alsa.rules = [
  {
    matches = [
      { device.name = "~alsa_card.*" }
    ]
    actions = {
      update-props = {
         device.disabled = true
      }
    }
  }
  {
    matches = [
      { device.name = "alsa_card.usb-Schiit_Audio_I_m_Fulla_Schiit-00" }
    ]
    actions = {
      update-props = {
        device.disabled = false
	device.profile.pro = true
      }
    }
  }
  {
    matches = [
      { device.name = "alsa_card.usb-R__DE_Microphones_R__DE_NT-USB_Mini_89C3EAB9-00" }
    ]
    actions = {
      update-props = {
        device.disabled = false
	device.profile.pro = true
      }
    }
  }
]
